### PR TITLE
Fix backward compatiblity for MDTrajTopology

### PR DESCRIPTION
**Pull request by dwhswenson**
This fixes a backward compatibility problem introduced in #1012:

```python
import openpathsampling as paths
paths.engines.openmm.topology.MDTrajTopology
```

After #1012:

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-95752f96565c> in <module>
----> 1 paths.engines.openmm.topology.MDTrajTopology

AttributeError: module 'openpathsampling.engines.openmm' has no attribute 'topology'
```

After this PR:

```
/Users/dwhs/miniconda3/envs/dev/bin/ipython:1: DeprecationWarning: openpathsampling.engines.openmm.topology.MDTrajTopology has been moved. Import MDTrajTopology from openpathsampling.engines instead.
  #!/Users/dwhs/miniconda3/envs/dev/bin/python
```

### CODE REVIEW

**Review by sroet — APPROVED** [review]
Huh, I am a bit surprised that worked before. Anyway, this LGTM

**Comment by dwhswenson** [comment]
> Huh, I am a bit surprised that worked before.

Yeah, I'm also not quite sure what's happening there. I can't create a minimal example that reproduces the working version. But it broke a test this morning, so I'll go ahead and merge this immediately.
