### PR TITLE
Only keep existing value stores in attribute_list

### LINKED ISSUE #762: restart not working
I wanted to do a restart of a toy system, and run into an ```AttributeError```
Running the following code:
```python
#Setup simple tps as in 
#OPS/examples/simple_tps/simple_tps.ipynb
import openpathsampling as paths

# always the most complicated bit
import openpathsampling.engines.toy as toys
import numpy as np

pes = (toys.OuterWalls([1.0,1.0], [0.0,0.0]) + 
       toys.Gaussian(-0.7, [12.0, 0.5], [-0.5, 0.0]) +
       toys.Gaussian(-0.7, [12.0, 0.5], [0.5, 0.0]))
topology = toys.Topology(n_spatial=2, masses=[1.0, 1.0], pes=pes)
engine = toys.Engine({'integ': toys.LangevinBAOABIntegrator(dt=0.02, temperature=0.1, gamma=2.5),
                              'n_frames_max': 5000,
                              'n_steps_per_frame': 10}, topology)
template = toys.Snapshot(coordinates=np.array([[0.0, 0.0]]),
                         velocities=np.array([[0.0, 0.0]]),
                        engine=engine)

# states are volumes in a CV space: define the CV
def xval(snapshot):
    return snapshot.xyz[0][0]

cv = paths.FunctionCV("xval", xval)

stateA = paths.CVDefinedVolume(cv, float("-inf"), -0.5).named("A")
stateB = paths.CVDefinedVolume(cv, 0.5, float("inf")).named("B")

network = paths.TPSNetwork(stateA, stateB)

scheme = paths.OneWayShootingMoveScheme(network, engine=engine)

# I'll fake an initial trajectory
trajectory = paths.Trajectory([
    toys.Snapshot(coordinates=np.array([[-.55+k*0.1, 0.0]]),
                  velocities=np.array([[0.1, 0.0]]),
                  engine=engine)
    for k in range(12)
])
initial_conditions = scheme.initial_conditions_from_trajectories(trajectory)
storage = paths.Storage("simple.nc", "w", template=template)
simulation = paths.PathSampling(storage, scheme, initial_conditions)
simulation.run(1
storage.close()
```
and then running
```python
#The rest follows OPS/examples/alanine_dipeptide_mstis/AD_mstis_3_restart.ipynb
resstore = paths.Storage("simple.nc", "a")
old_calc = resstore.pathsimulators[0]
old_calc.restart_at_step(resstore.steps[-1])
old_calc.run(1)
```  

this raises:
```
Working on Monte Carlo cycle number 2
Starting simulation...
Working on first step

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-5567891818e4> in <module>()
----> 1 old_calc.run(1)

/home/sander/github_files/openpathsampling/openpathsampling/pathsimulator.pyc in run(self, n_steps)
    734 
    735             self._current_step = mcstep
--> 736             self.save_current_step()
    737 
    738             # if self.storage is not None:

/home/sander/github_files/openpathsampling/openpathsampling/pathsimulator.pyc in save_current_step(self)
    600         """
    601         if self.storage is not None and self._current_step is not None:
--> 602             self.storage.steps.save(self._current_step)
    603 
    604     @classmethod

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/variable.pyc in _save(self, obj, idx)
     52     def _save(self, obj, idx):
     53         for var in self.var_names:
---> 54             self.write(var, idx, obj)
     55 
     56     def _load(self, idx):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in write(self, variable, idx, obj, attribute)
    357         val = getattr(obj, attribute)
    358 
--> 359         var[int(idx)] = val
    360 
    361         if var.var_type.startswith('lazy'):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    888                          for w in list.__iter__(v)]) \
    889                 if set_is_iterable(v) else \
--> 890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 
    892         elif var_type.startswith('lazyobj.'):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/movechange.pyc in _save(self, movechange, idx)
     21         self.vars['samples'][idx] = movechange.samples
     22         self.vars['input_samples'][idx] = movechange.input_samples
---> 23         self.vars['subchanges'][idx] = movechange.subchanges
     24         self.write('details', idx, movechange)
     25         self.vars['mover'][idx] = movechange.mover

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    887                 ''.join(['-' * 36 if w is None else str(UUID(int=store.save(w)))
    888                          for w in list.__iter__(v)]) \
--> 889                 if set_is_iterable(v) else \
    890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/movechange.pyc in _save(self, movechange, idx)
     21         self.vars['samples'][idx] = movechange.samples
     22         self.vars['input_samples'][idx] = movechange.input_samples
---> 23         self.vars['subchanges'][idx] = movechange.subchanges
     24         self.write('details', idx, movechange)
     25         self.vars['mover'][idx] = movechange.mover

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    887                 ''.join(['-' * 36 if w is None else str(UUID(int=store.save(w)))
    888                          for w in list.__iter__(v)]) \
--> 889                 if set_is_iterable(v) else \
    890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/movechange.pyc in _save(self, movechange, idx)
     21         self.vars['samples'][idx] = movechange.samples
     22         self.vars['input_samples'][idx] = movechange.input_samples
---> 23         self.vars['subchanges'][idx] = movechange.subchanges
     24         self.write('details', idx, movechange)
     25         self.vars['mover'][idx] = movechange.mover

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    887                 ''.join(['-' * 36 if w is None else str(UUID(int=store.save(w)))
    888                          for w in list.__iter__(v)]) \
--> 889                 if set_is_iterable(v) else \
    890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/movechange.pyc in _save(self, movechange, idx)
     21         self.vars['samples'][idx] = movechange.samples
     22         self.vars['input_samples'][idx] = movechange.input_samples
---> 23         self.vars['subchanges'][idx] = movechange.subchanges
     24         self.write('details', idx, movechange)
     25         self.vars['mover'][idx] = movechange.mover

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    887                 ''.join(['-' * 36 if w is None else str(UUID(int=store.save(w)))
    888                          for w in list.__iter__(v)]) \
--> 889                 if set_is_iterable(v) else \
    890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/movechange.pyc in _save(self, movechange, idx)
     19 
     20     def _save(self, movechange, idx):
---> 21         self.vars['samples'][idx] = movechange.samples
     22         self.vars['input_samples'][idx] = movechange.input_samples
     23         self.vars['subchanges'][idx] = movechange.subchanges

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    887                 ''.join(['-' * 36 if w is None else str(UUID(int=store.save(w)))
    888                          for w in list.__iter__(v)]) \
--> 889                 if set_is_iterable(v) else \
    890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/variable.pyc in _save(self, obj, idx)
     52     def _save(self, obj, idx):
     53         for var in self.var_names:
---> 54             self.write(var, idx, obj)
     55 
     56     def _load(self, idx):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in write(self, variable, idx, obj, attribute)
    357         val = getattr(obj, attribute)
    358 
--> 359         var[int(idx)] = val
    360 
    361         if var.var_type.startswith('lazy'):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    888                          for w in list.__iter__(v)]) \
    889                 if set_is_iterable(v) else \
--> 890                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    891 
    892         elif var_type.startswith('lazyobj.'):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/stores/object.py in save(self, obj, idx)
    892 
    893         try:
--> 894             self._save(obj, n_idx)
    895             self._auto_complete(obj, n_idx)
    896             self.cache[n_idx] = obj

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/trajectory.pyc in _save(self, trajectory, idx)
     11 
     12     def _save(self, trajectory, idx):
---> 13         self.vars['snapshots'][idx] = trajectory
     14         store = self.storage.snapshots
     15 

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

/home/sander/github_files/openpathsampling/openpathsampling/netcdfplus/netcdfplus.pyc in <lambda>(v)
    901                     '-' * 36 if w is None else str(UUID(int=store.save(w)))
    902                     for w in list.__iter__(v)
--> 903                 ]) if set_is_iterable(v) else \
    904                 '-' * 36 if v is None else str(UUID(int=store.save(v)))
    905 

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/snapshot_wrapper.py in save(self, obj, idx)
    369 
    370             self._save(obj, n_idx)
--> 371             self._auto_complete_single_snapshot(obj, n_idx)
    372             self._set_id(n_idx, obj)
    373         else:

/home/sander/github_files/openpathsampling/openpathsampling/storage/stores/snapshot_wrapper.py in _auto_complete_single_snapshot(self, obj, pos)
    420     def _auto_complete_single_snapshot(self, obj, pos):
    421         for cv, cv_store in self.attribute_list.items():
--> 422             if not cv_store.allow_incomplete:
    423                 value = cv._cache_dict._get(obj)
    424                 if value is None:

AttributeError: 'NoneType' object has no attribute 'allow_incomplete'
```
I fixed it by adding a couple of explicit 
 ```python 
if var is not None and ... :
```
in the files:
`openpathsampling/netcdfplus/stores/object.py` line `972` and line `1057`
`openpathsampling/storage/stores/snapshot_wrapper.py` line `422`

using `git bisect` I narrowed it down to the commits:

* dd16bb4ab7e228d60c0c7f92bdb38b66001df1a7
* 500e7c4378a7dbd9931919912e626fdae7f02cf7
* 82ea1d497c2937509f4ff8c654fbb5859c747a42
* c168e10273a3703032635d700e3a3529b0aedcaf

It looks like in commit `c168e10` in `netcdfplus/stores/attribute.py` allows `self.vars['cache'][idx]` to be `None`. And commit `500e7c4` in `netcdfplus/stores/object.py` allows for  `self.attribute_list[atribute]` to be set to this `None`.

I suspect everything that loops over `for a,b in object.attribute_list.items()` should explicitly check for `b is None`.

If you want I can create a PR to fix this.

### PR DESCRIPTION
**Pull request by jhprinz**
Resolves #762

### CODE REVIEW

**Comment by dwhswenson** [comment]
Since @hejung confirmed that this fixes the problem (https://github.com/openpathsampling/openpathsampling/issues/762#issuecomment-398677035) and tests pass, I'll merge!
